version: 2

models:
  - name: mrt_monthly_order_report
    description: "This model must contain relevant agregated information on orders, product und so weiter"
    columns:
      - name: order_id
        description: "Primary key, unique identifier for each order."
